description: contextiq evals
prompts:
  - "{{question}}"
providers:
  - id: file://provider.py:call_api
defaultTest:
  options:
    provider: anthropic:messages:claude-sonnet-4-6
tests: contextiq.yaml
outputPath: results/contextiq.json
